### ISSUE TITLE
Bidomain Stimulus Error

### ISSUE THREAD

**Issue by DUNBUJODA** [minrk/cbcbeat#1]
Hi,

I'm trying to run demo/bidomain-biventricular, but there is an issue.

```
error: expected primary-expression before ‘class’
 class Stimulus : public Expression
 ^~~~~

RuntimeError: Unable to compile C++ code with dijitso
```

Could you provide any suggestions? Thanks in advance!

Best,

**Comment by minrk** [comment]
Sorry, this isn't the cbcbeat repo, this is my old fork from some work years ago. I think you want https://github.com/ComputationalPhysiology/cbcbeat
